### ISSUE TITLE
Using jinja-to-js in a non-module context, small bug

### ISSUE THREAD

**Issue by wiltzius** [jonbretman/jinja-to-js#21]
Hi there,

I'm playing around with this project to see if we could use it to share template code between our client and server. So far it looks very promising!

Unfortunately, we use AngularJS dependency injection instead of modules and bower instead of npm for dependencies, which means installing the runtime was a bit of a challenge. I had to copy the runtime file, which isn't too big a big deal although it would be nice to have instructions to do so if you don't use npm.

Part of the challenge was due to one small bug: the module definition wrapper has a misnamed variable in the non-AMD, non-CommonJS case. `root` should be `global` in the immediately invoked expression at the top of the file.

This is trivial to fix, but if you'd like I'm happy to make a pull request.

Thanks!
Tom

**Comment by jonbretman** [comment]
Fixed in npm package `jinja-to-js@3.1.0`

**Comment by wiltzius** [comment]
Thanks!
